package me.zathrasnottheone.follow;

public class BlockTypes
{
	
	public enum SafetoWalk
	{
		RED_MUSHROOM,
	    BROWN_MUSHROOM,
	    SNOW,
	    ACACIA_SAPLING,
	    BAMBOO_SAPLING,
	    BIRCH_SAPLING,
	    DARK_OAK_SAPLING,
	    JUNGLE_SAPLING,
	    OAK_SAPLING,
	    SPRUCE_SAPLING,
	    POTTED_ACACIA_SAPLING,
	    POTTED_BIRCH_SAPLING,
	    POTTED_DARK_OAK_SAPLING,
	    POTTED_JUNGLE_SAPLING,
	    POTTED_OAK_SAPLING,
	    POTTED_SPRUCE_SAPLING,
	    TORCH,
	    REDSTONE,
	    REDSTONE_TORCH,
	    RED_TULIP,
	    CORNFLOWER,
	    SUNFLOWER,
	    WHEAT,
	    PUMPKIN_STEM,
	    LILY_PAD,
	    MELON_STEM,
	    SUGAR_CANE,
	    DEAD_BUSH,
	    TALL_GRASS,
	    ACACIA_SIGN,
	    BIRCH_SIGN,
	    DARK_OAK_SIGN,
	    JUNGLE_SIGN,
	    OAK_SIGN,
	    SPRUCE_SIGN,
	    ACACIA_WALL_SIGN,
	    BIRCH_WALL_SIGN,
	    DARK_OAK_WALL_SIGN,
	    JUNGLE_WALL_SIGN,
	    OAK_WALL_SIGN,
	    SPRUCE_WALL_SIGN,
	    STONE_BUTTON,
	    LEVER,
	    RAIL,
	    ACACIA_PRESSURE_PLATE,
	    BIRCH_PRESSURE_PLATE,
	    DARK_OAK_PRESSURE_PLATE,
	    JUNGLE_PRESSURE_PLATE,
	    OAK_PRESSURE_PLATE,
	    SPRUCE_PRESSURE_PLATE,
	    STONE_PRESSURE_PLATE
	    //Add wall torches, etc
	}
	
	public enum Slabs
	{
		ACACIA_SLAB,
		ANDESITE_SLAB,
	    BIRCH_SLAB,
	    BRICK_SLAB,
	    COBBLESTONE_SLAB,
	    CUT_RED_SANDSTONE_SLAB,
	    CUT_SANDSTONE_SLAB,
	    DARK_OAK_SLAB,
	    DARK_PRISMARINE_SLAB,
	    DIORITE_SLAB,
	    END_STONE_BRICK_SLAB,
	    GRANITE_SLAB,
	    JUNGLE_SLAB,
	    MOSSY_COBBLESTONE_SLAB,
	    MOSSY_STONE_BRICK_SLAB,
	    NETHER_BRICK_SLAB,
	    OAK_SLAB,
	    PETRIFIED_OAK_SLAB,
	    POLISHED_ANDESITE_SLAB,
	    POLISHED_DIORITE_SLAB,
	    POLISHED_GRANITE_SLAB,
	    PRISMARINE_BRICK_SLAB,
	    PRISMARINE_SLAB,
	    PURPUR_SLAB,
	    QUARTZ_SLAB,
	    RED_NETHER_BRICK_SLAB,
	    RED_SANDSTONE_SLAB,
	    SANDSTONE_SLAB,
	    SMOOTH_QUARTZ_SLAB,
	    SMOOTH_RED_SANDSTONE_SLAB,
	    SMOOTH_SANDSTONE_SLAB,
	    SMOOTH_STONE_SLAB,
	    SPRUCE_SLAB,
	    STONE_BRICK_SLAB,
	    STONE_SLAB
	}
	
	public enum Hazards
	{
		WATER,
	    LAVA,
	    FIRE,
	    CACTUS		
	}
	
	public enum Beds
	{
		BLACK_BED,
	    BLUE_BED,
	    BROWN_BED,
	    CYAN_BED,
	    GRAY_BED,
	    GREEN_BED,
	    LIGHT_BLUE_BED,
	    LIGHT_GRAY_BED,
	    LIME_BED,
	    MAGENTA_BED,
	    ORANGE_BED,
	    PINK_BED,
	    PURPLE_BED,
	    RED_BED,
	    WHITE_BED,
	    YELLOW_BED
	}
	
	public enum Fences
	{
		ACACIA_FENCE,
        BIRCH_FENCE,
        DARK_OAK_FENCE,
        JUNGLE_FENCE,
        NETHER_BRICK_FENCE,
        OAK_FENCE,
        SPRUCE_FENCE,
        ANDESITE_WALL,
        BRICK_WALL,
        COBBLESTONE_WALL,
        DIORITE_WALL,
        END_STONE_BRICK_WALL,
        GRANITE_WALL,
        MOSSY_COBBLESTONE_WALL,
        MOSSY_STONE_BRICK_WALL,
        NETHER_BRICK_WALL,
        PRISMARINE_WALL,
        RED_NETHER_BRICK_WALL,
        RED_SANDSTONE_WALL,
        SANDSTONE_WALL,
        STONE_BRICK_WALL,
        IRON_BARS
	}
	
	public enum Gates
	{
		ACACIA_FENCE_GATE,
        BIRCH_FENCE_GATE,
        DARK_OAK_FENCE_GATE,
        JUNGLE_FENCE_GATE,
        OAK_FENCE_GATE,
        SPRUCE_FENCE_GATE
	}
}